server:
  port: 5001

spring:
  application:
    name: Task-Management

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/task_management
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
